"use strict";

/**
 * Template data
 */
function index(environment, callback, data) {
    callback(null, data);
}

function level2(environment, callback, data) {
    setTimeout(function () {
        callback(null, data);
    }, Math.floor(Math.random() * 1500));
}

function level3(environment, callback, data) {
    var language = environment.language;
    var text;
    switch (language) {
        case 'de_DE':
            text = 'Die aktuelle Plattform Sprache ist Deutsch';
            break;
        case 'ro_RO':
            text = 'Limba curentă a platformei este Română';
            break;
        default:
            text = 'The current platform language is English';
    };
    setTimeout(function () {
        callback(null, {text: text});
    }, Math.floor(Math.random() * 3000));
}

function customer_error(environment, callback, data) {
    callback({
        errorMessage: 'This is an error generated by the customer\'s code.'
    }, data);
}

module.exports = {
    index: index,
    level2: level2,
    level3: level3,
    customer_error: customer_error
};
